### ISSUE TITLE
Subevent Relation Extraction清单某论文的相关性疑问

### ISSUE THREAD

**Issue by hummingg** [ZHEvent/ZHEvent.github.io#2]
论文《Graph Based Decoding for Event Sequencing and Coreference Resolution》好像不是关于Subevent Relation Extraction的？
文中说，“In this paper, we focus only on the After relations.”

**Comment by jsksxs360** [comment]
谢谢你的提醒！这篇文章确实不是关于包含关系的，而且之前已经放在[事件同指关系](https://github.com/ZHEvent/ZHEvent.github.io/blob/master/EventCoreference.md)页面下了，应该是整理时的错误。
